import type { Metadata } from 'next'
import React from 'react';

export const metadata: Metadata = {
    title: 'aaaaa',
    description: 'Generated by create next app',
}

const Meta = () => {
    return <>a</>
};

export default Meta;

